apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-forwarding-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 58255
    targetPort: 58255
    name: ssh-forwarding-ingress
  selector:
    app: tezos-remote-signer-forwarder
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer
spec:
  ports:
  - port: 8445
    name: remote-signer
  selector:
    app: tezos-remote-signer-forwarder
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tezos-remote-signer-forwarder-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tezos-remote-signer-forwarder
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 58255
      protocol: TCP
  - ports:
    - port: 8445
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: tezos-private-baking-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-remote-signer-forwarder
spec:
  selector:
    matchLabels:
      app: tezos-remote-signer-forwarder
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-remote-signer-forwarder
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - name: tezos-remote-signer-forwarder
        image: tezos-remote-signer-forwarder
        ports:
        - containerPort: 58255
          name: ssh
        - containerPort: 8443
          name: signer-a
        - containerPort: 8444
          name: signer-b
        env:
        - name: SIGNER_DATA
          valueFrom:
            configMapKeyRef:
              name: remote-signer-forwarder-configmap
              key: SIGNER_DATA
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      - name: tezos-remote-signer-loadbalancer
        image: tezos-remote-signer-loadbalancer
        ports:
        - containerPort: 8445
          name: signer
        env:
        - name: PUBLIC_BAKING_KEY
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: PUBLIC_BAKING_KEY
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
